FROM ubuntu:22.04 AS build
ARG LLVM_VERSION=15

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
      apt-get --no-install-recommends -y install \
      libboost-dev \
      libboost-test-dev \
      libboost-system-dev \
      libc6 \
      libc6-dev \
      libstdc++6 \
      g++ \
      autoconf \
      automake \
      python3 \
      pkg-config \
      libffi-dev \
      libz-dev \
      libzstd-dev \
      libtinfo-dev \
      libxml2-dev \
      wget ca-certificates \
      xz-utils \
      make \
      lsb-release \
      gnupg \
      software-properties-common

ADD --chmod=755 https://apt.llvm.org/llvm.sh /ci/
RUN /ci/llvm.sh ${LLVM_VERSION}

COPY . /nidhugg

RUN \
    /bin/bash -c \
    "cd /nidhugg && \
     autoreconf --install && \
     ./configure --prefix=/usr/local/ --with-llvm=/usr/lib/llvm-$LLVM_VERSION || (cat config.log; false) && \
     make -Csrc -j`nproc` all unittest"

SHELL ["/bin/bash", "-c"]
CMD make -C /nidhugg -j3 test
