FROM ubuntu:22.04 as build
ARG LLVM_VERSION=15.0.3

# COPY ci/install_deps.sh /ci/
RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
      apt-get --no-install-recommends -y install \
      libboost-dev \
      libboost-test-dev \
      libboost-system-dev \
      libc6 \
      libc6-dev \
      libstdc++6 \
      g++ \
      autoconf \
      automake \
      python3 \
      libffi-dev \
      libz-dev \
      libtinfo-dev \
      libxml2-dev \
      wget ca-certificates \
      xz-utils \
      cmake \
      make

ADD https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/llvm-project-$LLVM_VERSION.src.tar.xz /

RUN \
    /bin/bash -c \
    "cd / && \
     tar xf llvm-project-$LLVM_VERSION.src.tar.xz && \
     mkdir /build && \
     cd /build && \
     cmake -DCMAKE_INSTALL_PREFIX=/usr/local/       \
           -DCMAKE_BUILD_TYPE=MinSizeRel            \
           -DLLVM_TARGETS_TO_BUILD=""               \
           -DLLVM_LINK_LLVM_DYLIB=ON                \
           -DLLVM_OPTIMIZED_TABLEGEN=ON             \
           -DLLVM_ENABLE_ASSERTIONS=ON              \
           -DLLVM_ENABLE_PROJECTS="clang"           \
           /llvm-project-$LLVM_VERSION.src/llvm/ && \
     make -j`nproc` &&                              \
     cmake -DCMAKE_INSTALL_PREFIX=/usr/local -P cmake_install.cmake && \
     cd / && rm -r /build/ /llvm-project-$LLVM_VERSION.src/ && \
     (strip /usr/local/lib/*.so /usr/local/bin/* || true)"

COPY . /nidhugg

RUN \
    /bin/bash -c \
    "cd /nidhugg && \
     autoreconf --install && \
     (./configure --prefix=/usr/local/ --enable-asserts CXXFLAGS='-Og -g' \
                  LDFLAGS='-g -Wl,-rpath=/usr/local/lib/' \
      || (cat config.log; false)) && \
     make -Csrc -j`nproc` all unittest"

CMD make -C /nidhugg -j3 test
